---

- hosts: all
  ignore_errors: yes
  become: yes
  tasks:
        - name: Update packages to the latest version
          yum:
                name: '*'
                state: latest
          when: ansible_distribution == "CentOS"

        - name: Update all packages to the latest version
          apt:
                name: '*'
                state: latest
          when: ansible_distribution == "Ubuntu"
          
        - name: Install apache httpd 
          apt:
                name: apache2
                state: present
          when: ansible_distribution == "Ubuntu"
          
        - name: Install the latest version of Apache
          yum:
                name: httpd
                state: latest
         when: ansible_distribution == "CentOS"
         
       - name: Install a list of packages
         yum:
                name:
                  - nginx
                  - postgresql
                  - postgresql-server
                state: present
        when: ansible_distribution == "CentOS" 
        
